### ISSUE TITLE
Mod Utils won't export rotated cubes correctly.

### ISSUE THREAD

**Issue by davidkan2003** [JannisX11/blockbench-plugins#112]
If I have a cube with rotation, Mod Utils will export it unrotated in the .java file.
Appears to me now that Forge probably doesnt support rotated cubes, but then maybe at least expand the shape to fit the cube?

**Comment by JannisX11** [comment]
Does ModUtils export .java files? I don't think it does.

**Comment by JTK222** [comment]
VoxelShapes don't support rotations, that's why they are not exported.
That's not related to forge, but a vanilla limitation.
And I'm not going to add any form of automated generation for voxel shapes,
as an algorithm to optimize them would be overly complicated.
Therefore, creating and optimizing the VoxelShapes is the responsibility of the mod authors.
