### ISSUE TITLE
[BUG] [Minecraft Entity Wizard] [Minecraft Block Wizard] Export buttons don't show up in export tab

### ISSUE THREAD

**Issue by GeekTheSiren** [JannisX11/blockbench-plugins#315]
![Blockbench 12_21_2022 12_04_27 PM](https://user-images.githubusercontent.com/121192475/208977304-db570d08-4ad2-4a84-ba8b-ab66d471c49a.png)
![Blockbench 12_21_2022 12_04_42 PM](https://user-images.githubusercontent.com/121192475/208977307-a45714f3-0a2c-4122-a9c3-9855d63e3588.png)
In the export tab, there's supposed to be options to export your block/entity to your pack, but for whatever reason, yesterday those options disappeared. I've tried uninstalling and reinstalling both the plugins and Blockbench itself, as well as reloading the plugins, and the issue persists. Creation of packs works fine. The options are shown in the toolbar, but are always hidden when added.
![model geo - Blockbench 12_21_2022 1_31_28 PM](https://user-images.githubusercontent.com/121192475/208978381-9c0b3a61-997a-40aa-96d8-651b17ec146c.png)
If someone has a fix, please let me know!

**Comment by JannisX11** [comment]
That is totally normal. When using the Block or Entity Wizard plugin, you export an entire pack initially. For smartphone users there is also the option to export the MCAddon again while in the same session, since there is no direct file access.

After using the wizard, Blockbench is just a model editor. If you want to save changes to your model, press File > Save Model. If you want to edit the addon, use VS Code or Bridge instead.

Here is how to use the Block Wizard: https://www.youtube.com/watch?v=WnxMasZjmIc

**Comment by DroneMesh** [comment]
So after the initial export abilities. 
How can we export it again? 
Im sure there are many people facing the same issue. 
I had to redo my model 34 times. 
Can you provide us with the method to export as a .mcaddon after initial menu option disappears?
