### ISSUE TITLE
If statements cannot return a boolean

### ISSUE THREAD

**Issue by SebSemos** [JannisX11/blockbench-plugins#451]
`"pupil.visible": "if(var.blink>0.7&&var.blink2>0.5, false, true)",`

In the minecraft CEM animation editor, this prevent animations preview, but in game this line works fine.

**Comment by JannisX11** [comment]
@ewanhowell5195

**Comment by ewanhowell5195** [comment]
```
[OptiFine] net.optifine.expr.ParseException: Invalid argument type, function: "if", index: 1, type: BOOL, should be: FLOAT
```

This is an OptiFine limitation. The plugin works as intented.

This most likely works for you because you are not using OptiFine, but a CEM fabric mod. I strongly discourage the use of these mods when developing resource packs because they can have quirks like this one where they do not quite line up with OptiFine, making your pack only work on those mods. If you develop for OptiFine, then it will always work in both, since the mods goal is parity with OptiFine.

an if statement isnt even required in your code example. to fix your code, you need to instead change it to
```json
"pupil.visible": "!(var.blink > 0.7 && var.blink2 > 0.5)"
```

**Comment by ewanhowell5195** [comment]
just remembered one valid use for this:
```json
"varb.visible": "if(var.counter == 0, varb.check, varb.visible)"
```
has to be
```json
"varb.visible": "if(var.counter == 0, if(varb.check, 1, 0), if(varb.visible, 1, 0)) > 0"
```
